export const REASONS: { [key: string]: any } = {
  ready: 'From the Llama song titled Ready for the Ride',
  train: 'What Llama does to prep for MVs and Jett arms',
  pizza: 'This is Llama food',
  songs: 'Llama writes songs, sings songs, dances to songs...',
  laugh: 'What Llama does when trying to sing Three Million Years',
  tours: 'Llama performances and hopefully many more in the future!',
  eagle: 'Llama starred in the movie The Eagle and the Albatross',
  happy: 'General Llama and Llama fam sentiment :)',
  brass: 'From the Llama song Shake That Brass',
  mixes: 'Part of the song writing process',
  voice: 'Need this for songs',
  drink: 'We are talking about boba here...',
  demon: 'From song lyrics for Easier',
  scare: "Llama's favorite stream sound",
  tough: 'From song lyrics for Borders',
  dream: 'From song lyrics for Fantasy',
  cloud: "Llama's Chinese fan club name",
  adore: 'From song lyrics for Three Million Years',
  raids: 'Pokemon Go activity',
  money: "From song lyrics for Don't Dance",
  brain: "We're talking big brain energy",
  space: 'From song lyrics for Make It Better',
  stars: 'From song lyrics for Paradise',
  grass:
    "Part of Llama's favorite boba drink: honey lemon tea with boba and grass jelly",
  sings: 'What Llamas do',
  think: 'From song lyrics for Other People',
  swear: 'What Llama does on stream...quite a bit',
  sense: 'From song lyrics for On My Own',
  andro: 'Androgynous Llama',
  guide: 'From song lyrics for White Noise',
  write: 'Llama writes songs. Lots of them.',
  twist: 'From song lyrics for Neon',
  games: 'What Llama plays on stream',
  drunk: 'Llama is lightweight',
  shout: 'From song lyrics for Numb',
  adult: 'When Llama does taxes. Also because "adulting sucks"',
  wanna: 'From song lyrics for I Just Wanna',
  tight: 'From song lyrics for Paradise',
  virgo: "Llama's astrological sign",
  youth: 'Llama participated in a reality show called Invincible Youth',
  drive: 'From song lyrics for Vegas',
  group: 'Llama was part of girl group f(x)',
  speak: 'From song lyrics for Stay Calm',
  jacks: 'Jackjack did not fit in 5 letters',
  super: "Llama featured on Superfruit's song Fantasy",
  throw: 'From song lyrics for Paradise',
  funny: 'Llama is funny',
  cross: 'From song lyrics for Borders',
  lemon:
    "Part of Llama's favorite boba drink: honey lemon tea with boba and grass jelly",
  sugar: 'From song lyrics for Paradise',
  shoes: 'Llama has some sweet kicks',
  sweet: 'From song lyrics for Other People',
  apple: 'What the pineAPPLE',
  climb: 'From song lyrics for High Hopes',
  steel: 'Llama is a part of Steelwool Entertainment',
  enjoy: 'From song lyrics for Three Million Years',
  story: 'Songs tell a story',
  point: 'From song lyrics for Complicated',
  merch: 'Save your money for merch!',
  place: 'From song lyrics for Other People',
  birbs: 'Roommate Tricia + Llama = birbs',
  scars: 'From song lyrics for Easier',
  meows: 'What Llama says randomly',
  light: 'Llama did a cover of One More Light with Gen Neo',
  movie: 'Llama movies: The Eagle and the Albatross, We Bare Bears: The Movie',
  party: 'Every Llama stream is a party',
  black: 'From song lyrics for Neon',
  gamer: "Because that's what Llama is",
  spice: 'From song lyrics for Paradise',
  owata:
    "Llama's answer for Dive Studios Hwaiting pop quiz. Her version of Ottawa.",
  taste: 'From song lyrics for Stay Calm',
  jelly:
    "Part of Llama's favorite boba drink: honey lemon tea with boba and grass jelly",
  heals: 'From song lyrics for Lifeline',
  skate: "One of Llama's favorite hobbies: skateboarding",
  awake: 'From song lyrics for On My Own',
  again: 'From song title Breathe Again, a collaboration with Ksuke',
  kicks: 'Llama likes shoes',
  beats: 'Llama makes music to beats',
  spawn: 'A reference to Valorant which Llama plays',
  juice: "Llama's favorite juice is Jamba Juice even though there is no boba",
  blind: 'From song lyrics for Hands Behind My Back',
  hyped: 'How Llama describes her excitement',
  tears: 'From song lyrics for Easier',
  learn: 'Because Llama is always learning',
  floor: 'From song lyrics for Shake That Brass',
  ideas: 'What Llama has for songs',
  shine: 'From song lyrics for High Hopes',
  first: 'Because Llama always beats Kirby stages on the "FIRST TRY"',
  phase: 'From song lyrics for White Noise',
  spoon:
    'Spoons make a beat when falling down stairs. (From Grammy museum interview)',
  chase: 'From song lyrics for I Just Wanna',
  drums: 'What Llama played on tour',
  crazy: 'From song lyrics for Bad Decisions',
  edits: 'Part of the song and MV making process',
  break: 'From song lyrics for Curiosity',
  snacc: 'Common saying: "Attacc with snacc"',
  chalk: 'From song lyrics for Bad Decisions',
  storm: 'From song title Perfect Storm, a collaboration with Miyavi',
  drown: 'From song lyrics for Numb',
  kirby: 'Game played on stream. Always winning on the first try!',
  lungs: 'From song lyrics for High Hopes',
  chats: 'What Llama does on stream/discord',
  board: 'Llama hobby: skateboarding',
  stair: 'A reference to Pokemon Arceus',
  scene: 'From song lyrics for Neon',
  catch: "Gotta catch 'em all! (Pokemon)",
  stand: 'From song lyrics for Borders',
  loved: 'Because Llama is loved by her fans. Shoutout Llama fam!',
  jamba: "Llama's favorite juice is Jamba Juice even though there is no boba",
  fight: 'From song lyrics for Borders',
  thank: 'Because Llama and Llama fam are thankful',
  tease: 'From song lyrics for Paradise',
  gummy: "One of Llama's favorite candies",
  honey:
    "Part of Llama's favorite boba drink: honey lemon tea with boba and grass jelly",
  sober: 'From song lyrics for I Love Somebody',
  words: 'Llama uses a lot of them to make music',
}
